server:
  port: 8006
spring:
  application:
    name: kafka-demo
  kafka:
    # kafka 服务地址，多个以,分割
    bootstrap-servers: localhost:9092
    producer:
      # 消息发送失败后的重试次数, 0为不启用重试机制, 当leader节点不可用时，一个repli节点会代替成为leader，会导致消息发送失败
      retries: 3
      # 批量发送的数量
      batch-size: 1000
      # 生产者可用的缓存大小
      buffer-memory: 33554432
      # 键值的序列化
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      # 生产者要求leader节点在完成请求前需要的的确认数， 0表示不需要确认，1表示leader节点确认写入日志后，即可确认，all表示所有的ISR节点都要确认
      acks: 1
    consumer:
      # 消费者组
      group-id: kafka-demo
      # 是否开启自动提交，如果开启，消费者会在消费消息后自动提交offset，如果消费失败，会导致消息丢失
      enable-auto-commit: false
      # 自动提交的时间间隔，毫秒， 当enable-auto-commit为true时，生效
      auto-commit-interval: 1000
      # 从最早的消息开始读取，smallest表示从最早的消息开始读取，largest表示从最新的消息开始读取
      auto-offset-reset: latest
      # 键值序列化
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # 每次最大拉取的消息数量
      max-poll-records: 4000
    listener:
      # 消费者ack模式
      ack-mode: manual_immediate
