server:
  port: 8003
spring:
  application:
    name: mybatis-demo
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis_demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql
    druid:
      connect-timeout: 1000
      max-active: 100
      max-wait: 2000
      min-idle: 10
      validationQuery: select 1
      validationQueryTimeout: 3
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl