server:
  port: 8004
spring:
  application:
    name: jpa-demo
  datasource:
    url: jdbc:mysql://192.168.31.228:3306/jpa_demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql
  jpa:
    show-sql: true